version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule: 
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 4
    schedule:
      interval: "daily"
